version: '3.8'

services:
  graphiti:
    image: ghcr.io/vaenow/graphiti-mcp:latest
    container_name: graphiti-app
    ports:
      - "7474:7474"   # Neo4j HTTP interface
      - "7687:7687"   # Neo4j Bolt protocol
      - "8000:8000"   # Graphiti application port
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://localhost:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - USE_PARALLEL_RUNTIME=false
      - GRAPHITI_TELEMETRY_ENABLED=true
    volumes:
      - graphiti_data:/var/lib/neo4j/data
      - graphiti_logs:/var/lib/neo4j/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  graphiti_data:
    driver: local
  graphiti_logs:
    driver: local

# Example usage:
# 1. Set your OpenAI API key: export OPENAI_API_KEY=your_key_here
# 2. Start the service: docker-compose up -d
# 3. Access Neo4j Browser: http://localhost:7474
# 4. View logs: docker-compose logs -f 